/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.appCitas.vistas;

import Desvanecido.Efecto;
import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JDialog;

/**
 *
 * @author Gabriel Dubuc
 */
public class Aceptado extends JDialog {

    private int xMouse, yMouse;
    private Efecto fade;
    
    /**
     * Creates new form Aceptar
     */
    public Aceptado() {
        initComponents();
        this.setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
        fade=new Efecto(this);
        eventos();   
        
    }
    
    public Aceptado(Login login) {
        super(login, true);
        initComponents();
        this.setLocationRelativeTo(this);
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30);
        AWTUtilities.setWindowShape(this, forma);
        fade=new Efecto(this);
        eventos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroud_aceptacion = new javax.swing.JPanel();
        logo_aceptado = new javax.swing.JLabel();
        titulo_bienvenido = new javax.swing.JLabel();
        margenes_boton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        backgroud_aceptacion.setBackground(new java.awt.Color(147, 100, 68));
        backgroud_aceptacion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                backgroud_aceptacionMouseDragged(evt);
            }
        });
        backgroud_aceptacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                backgroud_aceptacionMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backgroud_aceptacionMousePressed(evt);
            }
        });
        backgroud_aceptacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logo_aceptado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo_aceptado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/notificacion_aceptacion.png"))); // NOI18N
        backgroud_aceptacion.add(logo_aceptado, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 20, 290, 100));

        titulo_bienvenido.setFont(new java.awt.Font("Roboto Black", 0, 24)); // NOI18N
        titulo_bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        titulo_bienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_bienvenido.setText("BIENVENIDO !");
        backgroud_aceptacion.add(titulo_bienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 300, 40));

        margenes_boton.setBackground(new java.awt.Color(147, 100, 68));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/notificacion_continuar.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout margenes_botonLayout = new javax.swing.GroupLayout(margenes_boton);
        margenes_boton.setLayout(margenes_botonLayout);
        margenes_botonLayout.setHorizontalGroup(
            margenes_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(margenes_botonLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        margenes_botonLayout.setVerticalGroup(
            margenes_botonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(margenes_botonLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        backgroud_aceptacion.add(margenes_boton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 300, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud_aceptacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backgroud_aceptacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backgroud_aceptacionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroud_aceptacionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroud_aceptacionMouseEntered

    private void backgroud_aceptacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroud_aceptacionMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
        
    }//GEN-LAST:event_backgroud_aceptacionMousePressed

    private void backgroud_aceptacionMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroud_aceptacionMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - this.xMouse, y - this.yMouse);
    }//GEN-LAST:event_backgroud_aceptacionMouseDragged

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        fade.cerrar(100);
        this.dispose();
    }//GEN-LAST:event_jLabel3MouseClicked
  
    private void eventos(){
        addWindowListener(new java.awt.event.WindowAdapter() {        
            @Override
            public void windowActivated(java.awt.event.WindowEvent evt){
                fade.abrir(100);
            }      
        });
    }   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Aceptado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Aceptado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Aceptado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Aceptado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Aceptado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroud_aceptacion;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel logo_aceptado;
    private javax.swing.JPanel margenes_boton;
    private javax.swing.JLabel titulo_bienvenido;
    // End of variables declaration//GEN-END:variables
}
