/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.appCitas.vistas;

import Desvanecimiento.Desvanecimiento;
import com.appCitas.controladores.controladoresMenu;
import java.awt.Color;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel Dubuc
 */
public class Menu extends javax.swing.JFrame {
    
    private controladoresMenu conMenu;
    private int xMouse, yMouse;
    private Desvanecimiento efecto;
    private String idUsuario;
    /**
     * Creates new form Menu
     */
    public Menu() {
        conMenu=new controladoresMenu();
        initComponents();
        this.setLocationRelativeTo(this);

        efecto=new Desvanecimiento();
        efecto.Abrir(this, 25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_background = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        btn_home = new rojerusan.RSButtonIconI();
        btn_citas = new rojerusan.RSButtonIconI();
        btn_usuarios = new rojerusan.RSButtonIconI();
        btn_clientes = new rojerusan.RSButtonIconI();
        btn_acerca = new rojerusan.RSButtonIconI();
        jLabel1 = new javax.swing.JLabel();
        lblfoto = new javax.swing.JLabel();
        panel_cart = new javax.swing.JPanel();
        panel_cerrar = new javax.swing.JPanel();
        lbl_cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        menu_background.setBackground(new java.awt.Color(255, 255, 255));
        menu_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_menu.setBackground(new java.awt.Color(147, 100, 68));

        btn_home.setBackground(new java.awt.Color(147, 100, 68));
        btn_home.setBorder(null);
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/Menu_home.png"))); // NOI18N
        btn_home.setText("HOME");
        btn_home.setBorderPainted(false);
        btn_home.setColorHover(new java.awt.Color(134, 91, 68));
        btn_home.setFocusable(false);
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_home.setSelected(true);
        btn_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_homeMouseClicked(evt);
            }
        });
        btn_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_homeActionPerformed(evt);
            }
        });

        btn_citas.setBackground(new java.awt.Color(147, 100, 68));
        btn_citas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/Menu_citas.png"))); // NOI18N
        btn_citas.setText("CITAS");
        btn_citas.setBorderPainted(false);
        btn_citas.setColorHover(new java.awt.Color(134, 91, 68));
        btn_citas.setFocusable(false);
        btn_citas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_citas.setMargin(new java.awt.Insets(2, 14, 2, 12));

        btn_usuarios.setBackground(new java.awt.Color(147, 100, 68));
        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/Menu_usuarios.png"))); // NOI18N
        btn_usuarios.setText("USUARIOS");
        btn_usuarios.setBorderPainted(false);
        btn_usuarios.setColorHover(new java.awt.Color(134, 91, 68));
        btn_usuarios.setFocusable(false);
        btn_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_usuarios.setMargin(new java.awt.Insets(2, 34, 2, 0));

        btn_clientes.setBackground(new java.awt.Color(147, 100, 68));
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/Menu_clientes.png"))); // NOI18N
        btn_clientes.setText("CLIENTES");
        btn_clientes.setBorderPainted(false);
        btn_clientes.setColorHover(new java.awt.Color(134, 91, 68));
        btn_clientes.setFocusable(false);
        btn_clientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_clientes.setMargin(new java.awt.Insets(2, 31, 2, 0));

        btn_acerca.setBackground(new java.awt.Color(147, 100, 68));
        btn_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/appCitas/recursos/Menu_acerca.png"))); // NOI18N
        btn_acerca.setText("ACERCA DE");
        btn_acerca.setBorderPainted(false);
        btn_acerca.setColorHover(new java.awt.Color(134, 91, 68));
        btn_acerca.setFocusable(false);
        btn_acerca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btn_acerca.setMargin(new java.awt.Insets(2, 41, 2, 0));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NOMBRE Y APELLIDO");

        javax.swing.GroupLayout panel_menuLayout = new javax.swing.GroupLayout(panel_menu);
        panel_menu.setLayout(panel_menuLayout);
        panel_menuLayout.setHorizontalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_home, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_citas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_acerca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(panel_menuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_menuLayout.setVerticalGroup(
            panel_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menuLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_citas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_acerca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70))
        );

        menu_background.add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 500));

        panel_cart.setBackground(new java.awt.Color(255, 255, 255));

        panel_cerrar.setBackground(new java.awt.Color(255, 255, 255));

        lbl_cerrar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_cerrar.setText("X");
        lbl_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbl_cerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panel_cerrarLayout = new javax.swing.GroupLayout(panel_cerrar);
        panel_cerrar.setLayout(panel_cerrarLayout);
        panel_cerrarLayout.setHorizontalGroup(
            panel_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
        );
        panel_cerrarLayout.setVerticalGroup(
            panel_cerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_cartLayout = new javax.swing.GroupLayout(panel_cart);
        panel_cart.setLayout(panel_cartLayout);
        panel_cartLayout.setHorizontalGroup(
            panel_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_cartLayout.createSequentialGroup()
                .addGap(0, 558, Short.MAX_VALUE)
                .addComponent(panel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panel_cartLayout.setVerticalGroup(
            panel_cartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_cartLayout.createSequentialGroup()
                .addComponent(panel_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 472, Short.MAX_VALUE))
        );

        menu_background.add(panel_cart, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 600, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menu_background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation( x - this.xMouse, y - this.yMouse);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void btn_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_homeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeMouseClicked

    private void lbl_cerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseEntered
        // TODO add your handling code here:
        panel_cerrar.setBackground(Color.red);
        lbl_cerrar.setForeground(Color.white);
    }//GEN-LAST:event_lbl_cerrarMouseEntered

    private void lbl_cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseClicked
        // TODO add your handling code here:
        efecto.Cerrar(this, 25);
    }//GEN-LAST:event_lbl_cerrarMouseClicked

    private void lbl_cerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_cerrarMouseExited
        // TODO add your handling code here:
        panel_cerrar.setBackground(Color.white);
        lbl_cerrar.setForeground(Color.black);
    }//GEN-LAST:event_lbl_cerrarMouseExited

    private void btn_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_homeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_homeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    
    private void datosUsuario(){ 
       
        jLabel1.setText(conMenu.nombreUsuario(idUsuario));
        lblfoto.setIcon(conMenu.getImagen(idUsuario));
    }
    
    public void setIdUsuario(String idUsuario){
        this.idUsuario=idUsuario;
        datosUsuario();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSButtonIconI btn_acerca;
    private rojerusan.RSButtonIconI btn_citas;
    private rojerusan.RSButtonIconI btn_clientes;
    private rojerusan.RSButtonIconI btn_home;
    private rojerusan.RSButtonIconI btn_usuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_cerrar;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JPanel menu_background;
    private javax.swing.JPanel panel_cart;
    private javax.swing.JPanel panel_cerrar;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}
